export const questions = [
    {
        question: 'Ramus father has 4 sons Raju, Ranu, Ronnie, so tell me what is the name of the 4th son?',
        option1: 'Shamu',
        option2: 'Damu',
        option3: 'Ramu',
        option4: 'Raju',
        ans: 3,
    },
    {
        question: ' What month of the year has 28 days?',
        option1: 'January',
        option2: 'September',
        option3: 'March',
        option4: 'All of Them',
        ans: 4,
    },
    {
        question: 'What can you break, even if you never pick it up or touch it?',
        option1: 'Glass',
        option2: 'Pen',
        option3: 'Promise',
        option4: 'All of Them',
        ans: 3,
    },
    {
        question: 'I Have Four Fingers and Thumb, But Iam Not Living. What am I?',
        option1: 'Table',
        option2: 'Chair',
        option3: 'Glove',
        option4: 'Fan',
        ans: 3,
    },
    {
        question: 'what is the name of Elon Musks Son?',
        option1: 'Raju',
        option2: 'Stephen',
        option3: 'X Æ A-Xii',
        option4: 'Alexander',
        ans: 3,
    },
    {
        question: 'You Hold My Tail While I Fish For You. What am I?',
        option1: 'Net',
        option2: 'Monkey',
        option3: 'Canoe',
        option4: 'Bucket',
        ans: 1,
    },
    {
        question: 'What is full of Holes but still holds water?',
        option1: 'Sponge',
        option2: 'Bucket',
        option3: 'Plate',
        option4: 'Galor',
        ans: 1,
    },
    {
        question: 'Everybody has me but nobody can lose me . What am I?',
        option1: 'Shadow',
        option2: 'Monkey',
        option3: 'Shoes',
        option4: 'Pen',
        ans: 1,
    },
    {
        question: 'what can you catch but cant throw?',
        option1: 'Ball',
        option2: 'Cold',
        option3: 'Tennis',
        option4: 'Bird',
        ans: 2,
    },
    {
        question: 'I belong to you but others uses me more than you do. what am I?',
        option1: 'Brain',
        option2: 'Shadow',
        option3: 'Name',
        option4: 'Hand',
        ans: 3,
    }
]